### ISSUE TITLE
[BUG] Security rule must specify SourceAddressPrefixes, SourceAddressPrefix, or SourceApplicationSecurityGroups.

### ISSUE THREAD

**Issue by patricknick** [claranet/terraform-azurerm-nsg#11]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### OpenTofu Version

1.10.0

### AzureRM Provider Version

4.38.1

### Affected Resource(s)/Data Source(s)

azurerm_network_security_rule

### OpenTofu Configuration Files

```hcl
terraform {
  required_version = ">=1.10.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=4.38"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "main" {
  name     = "rg-bug-repro"
  location = "West Europe"
}

resource "azurerm_virtual_network" "main" {
  name                = "vnet-bug-repro"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
}

module "subnet" {
  source  = "claranet/subnet/azurerm"
  version = "8.1.0"

  environment    = "test"
  location_short = "we"
  client_name    = "clientname"
  stack          = "stack"

  resource_group_name = azurerm_resource_group.main.name

  virtual_network_name = azurerm_virtual_network.main.name
  cidrs                = ["10.0.1.0/24"]

  network_security_group_name = module.network_security_group.name
}

module "network_security_group" {
  source  = "claranet/nsg/azurerm"
  version = "8.1.0"

  client_name    = "clientname"
  environment    = "dev"
  stack          = "stack"
  location       = "westeurope"
  location_short = "we"

  resource_group_name = azurerm_resource_group.main.name

  http_inbound_allowed  = true
  https_inbound_allowed = true
}
```

### Debug Output/Panic Output

```shell
not required
```

### Expected Behaviour

The module should validate my module inputs and force me to set `http_source_allowed` and `https_source_allowed` respectively. This should be feasible with another condition on these variables.

(According to the error output, one could also set `SourceApplicationSecurityGroups`, but I don't see that option offered by this module.)

### Actual Behaviour

`tofu apply` fails with the following error from Azure:

```console
Error: creating Security Rule (Subscription: "bd2b67b8-d558-404a-a501-004657801a60"
│ Resource Group Name: "rg-bug-repro"
│ Network Security Group Name: "nsg-stack-clientname-we-dev"
│ Security Rule Name: "http-inbound"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: SecurityRuleParametersMissing: Required security rule parameters are missing for security rule with Id: /subscriptions/bd2b67b8-d558-404a-a501-004657801a60/resourceGroups/rg-bug-repro/providers/Microsoft.Network/networkSecurityGroups/nsg-stack-clientname-we-dev/securityRules/http-inbound. Security rule must specify SourceAddressPrefixes, SourceAddressPrefix, or SourceApplicationSecurityGroups.
│ 
│   with module.network_security_group.azurerm_network_security_rule.http_inbound[0],
│   on .terraform/modules/network_security_group/r-nsg.tf line 37, in resource "azurerm_network_security_rule" "http_inbound":
│   37: resource "azurerm_network_security_rule" "http_inbound" {
│ 
╵
╷
│ Error: creating Security Rule (Subscription: "bd2b67b8-d558-404a-a501-004657801a60"
│ Resource Group Name: "rg-bug-repro"
│ Network Security Group Name: "nsg-stack-clientname-we-dev"
│ Security Rule Name: "https-inbound"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: SecurityRuleParametersMissing: Required security rule parameters are missing for security rule with Id: /subscriptions/bd2b67b8-d558-404a-a501-004657801a60/resourceGroups/rg-bug-repro/providers/Microsoft.Network/networkSecurityGroups/nsg-stack-clientname-we-dev/securityRules/https-inbound. Security rule must specify SourceAddressPrefixes, SourceAddressPrefix, or SourceApplicationSecurityGroups.
│ 
│   with module.network_security_group.azurerm_network_security_rule.https_inbound[0],
│   on .terraform/modules/network_security_group/r-nsg.tf line 60, in resource "azurerm_network_security_rule" "https_inbound":
│   60: resource "azurerm_network_security_rule" "https_inbound" {
```

### Steps to Reproduce

1. `tofu validate` --> successful
2. `tofu plan` --> successful
3. `tofu apply` --> fails at creating the NSRs

**Comment by BzSpi** [comment]
This may be related to this change merged on version 4.38.0 https://github.com/hashicorp/terraform-provider-azurerm/pull/29675

We will investigate and fix, thanks for noticing.

**Comment by BzSpi** [comment]
This bug may have been fixed since, there are several issues related to it that have been merged in later versions.

Can you please retry with the latest version of the provider, ie 4.40.0 ?

Possible linked issues:
* https://github.com/hashicorp/terraform-provider-azurerm/issues/30280
* https://github.com/hashicorp/terraform-provider-azurerm/issues/29619

**Comment by patricknick** [comment]
Sorry for the late reply, the notification slipped my attention. 

I just tried the example above again with AzureRM provider version 4.44.0. However, I still experience the same behaviour.

**Comment by Shr3ps** [comment]
Thanks for the reply, we will lookt into it

**Comment by BzSpi** [comment]
Hello @patricknick 

You have to specify the allowed source when enabling a pre-defined rule. We've updated the module to have specific validation error.
Hope this help.

Regards
